[DB]
host=120.24.235.106
username=python
password=python666
db_name=test
port=3306

[IP]
#测试环境
ip=119.89.0.45
#开发环境
#ip=119.89.0.66

[lineno]
#控制读取指定行的数据 all读取所有 [2,3]否则读取第二行第三行
line=all
#line =[2,3]

[LOGCAT]
level1=